## Numpy Practice

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
x = [1,2,3,4,5]
y = np.array(x)

In [5]:
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
ar2 = np.array([[1,2,3,4], [5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [10]:
ar3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [13]:
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
