## Numpy Practice

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
x = [1,2,3,4,5]
y = np.array(x)

In [5]:
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
ar2 = np.array([[1,2,3,4], [5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [10]:
ar3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [13]:
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Special numpy arrays

In [14]:
import numpy as np

In [18]:
ar_zero = np.zeros(4)
ar_2z = np.zeros((3,4))
print(ar_zero)
print()
print(ar_2z)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
ar_one = np.ones(5)
ar_2one = np.ones((4,2))
print(ar_one)
print()
print(ar_2one)

[1. 1. 1. 1. 1.]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
ar_em = np.empty(5)
print(ar_em)

[1. 1. 1. 1. 1.]


In [25]:
ar_rng = np.arange(5)
print(ar_rng)

[0 1 2 3 4]


In [30]:
ar_dia = np.eye(4,4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
ar_lin = np.linspace(0,20, num = 5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# Random functions

In [34]:
import numpy as np

In [35]:
var = np.random.rand(4)
print(var)

[0.99177407 0.25416304 0.72603762 0.19877428]


In [36]:
var1 = np.random.rand(2,5)
print(var1)

[[0.58764975 0.75670403 0.96925159 0.1805577  0.94636683]
 [0.87335347 0.92395493 0.61747188 0.90401706 0.14741869]]


In [37]:
varn = np.random.randn(5)
print(varn)

[ 1.09368511  0.22966137  0.02615756 -2.14902563  0.74878239]


In [38]:
varnd = np.random.randn(3,4)
print(varnd)

[[ 1.25417603 -1.16851994  0.62973363 -0.54062229]
 [ 0.35662221  0.24974486 -0.21078632 -0.03483389]
 [ 0.23108073  1.8352828  -0.43000531 -0.61370377]]


In [39]:
varf = np.random.ranf(4)
print(varf)

[0.35652869 0.97374752 0.70756212 0.04898589]


In [45]:
varr = np.random.randint(5, 20, 5)
print(varr)

[17 10  9 19 10]


# Data Types

In [46]:
import numpy as np

In [50]:
var = np.array([1,"2",3,4,5])
print("Data type: ", var.dtype)

Data type:  <U11


In [58]:
arrd = np.array([1,2,3,4], dtype = "f")
print(arrd.dtype)

float32


In [59]:
varty = arrd.astype(int)
print(arrd)
print(varty)

[1. 2. 3. 4.]
[1 2 3 4]


# Shaping and Reshaping of numpy arrays

In [60]:
import numpy as np

In [63]:
vars = np.array([[1,2,3],[4,5,6]])
print(vars)
print()
print(vars.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [67]:
varmul = np.array([1,2,3], ndmin = 7)
print(varmul)
print()
print(varmul.shape)

[[[[[[[1 2 3]]]]]]]

(1, 1, 1, 1, 1, 1, 3)


In [71]:
varres = np.array([1,2,3,4,5,6])
x = varres.reshape(3,2)
print(x.ndim)
print(x.shape)
print(x)

2
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [82]:
varry = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(varry)
print(varry.ndim)
print(varry.shape)
print()

vres = varry.reshape(2,3,2)
print(vres)
print(vres.ndim)
print(vres.shape)
print()

v1 = vres.reshape(-1)
print(v1)
print(v1.ndim)
print(v1.shape)
print()

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)



# Arithmetic ops in numpy arrays

In [83]:
import numpy as np

In [84]:
vara = np.array([1,2,3,4,5])
varad = vara + 5
print(varad)

[ 6  7  8  9 10]


In [92]:
var1 = np.array([1,2,3])
var2 = np.array([4,5,6])

nvar = np.add(var1,var2)
print(nvar)

[5 7 9]


In [94]:
var1 = np.array([1,2,3])
var2 = np.array([4,5,6])

nvar = np.subtract(var1,var2)
print(nvar)

[-3 -3 -3]


In [95]:
var1 = np.array([1,2,3])
var2 = np.array([4,5,6])

nvar = np.multiply(var1,var2)
print(nvar)

[ 4 10 18]


In [96]:
var1 = np.array([1,2,3])
var2 = np.array([4,5,6])

nvar = np.divide(var1,var2)
print(nvar)

[0.25 0.4  0.5 ]


In [98]:
var1 = np.array([1,2,3])
var2 = np.array([4,5,6])

nvar = np.mod(var1,var2)
print(nvar)

[1 2 3]


In [99]:
var1 = np.array([1,2,3])
var2 = np.array([4,5,6])

nvar = np.power(var1,var2)
print(nvar)

[  1  32 729]


In [101]:
var1 = np.array([1,2,3])
var2 = np.array([4,5,6])

nvar = np.reciprocal(var1)
print(nvar)

[1 0 0]


In [104]:
var1 = np.array([[1,2,3],[2,4,2]])
var2 = np.array([[4,5,6],[1,2,1]])

nvar = np.add(var1,var2)
print(nvar)
print()
nvar = np.subtract(var1,var2)
print(nvar)
print()
nvar = np.multiply(var1,var2)
print(nvar)
print()
nvar = np.divide(var1,var2)
print(nvar)
print()
nvar = np.mod(var1,var2)
print(nvar)
print()
nvar = np.power(var1,var2)
print(nvar)
print()

[[5 7 9]
 [3 6 3]]

[[-3 -3 -3]
 [ 1  2  1]]

[[ 4 10 18]
 [ 2  8  2]]

[[0.25 0.4  0.5 ]
 [2.   2.   2.  ]]

[[1 2 3]
 [0 0 0]]

[[  1  32 729]
 [  2  16   2]]



In [118]:
# for 1d arrays

nv = np.array([1,2,3,4,5,6,2,6])
print("min value: ", np.min(nv))
print("min value pos: ", np.argmin(nv))
print("max value: ", np.max(nv))
print("max value pos: ", np.argmax(nv))
print(np.sqrt(nv))
print(np.cumsum(nv))

min value:  1
min value pos:  0
max value:  6
max value pos:  5
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 1.41421356 2.44948974]
[ 1  3  6 10 15 21 23 29]


In [115]:
# for 2d arrays
# axis = 0 (finds along columns)
# axis = 1 (find along rows)

nv2 = np.array([[1,2,5,6], [3,4,8,2]])
print("min value along column: ", np.min(nv2, axis = 0))
print("min value along row: ", np.min(nv2, axis = 1))

min value along column:  [1 2 5 2]
min value along row:  [1 2]


# Broadcasting in numpy

In [119]:
import numpy as np

In [121]:
v1 = np.array([1,2,3,4])
v2 = np.array([1,2,3,4])
print(np.add(v1, v2))

[2 4 6 8]


In [124]:
ar1 = np.array([1,2,3])
print(ar1.shape)
print(ar1)
print()
ar2 = np.array([[1],[2],[3]])
print(ar2.shape)
print(ar2)
print()

nar = np.add(ar1, ar2)
print(nar.shape)
print(nar)

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]

(3, 3)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [131]:
ar1 = np.array([[1,2,3],[1,2,3]])
print(ar1.shape)
print(ar1)
print()
ar2 = np.array([[1],[2]])
print(ar2.shape)
print(ar2)
print()

nar = np.add(ar1, ar2)
print(nar.shape)
print(nar)

(2, 3)
[[1 2 3]
 [1 2 3]]

(2, 1)
[[1]
 [2]]

(2, 3)
[[2 3 4]
 [3 4 5]]


# Indexing

In [132]:
import numpy as np

In [148]:
# 1d array

ar1 = np.array([1,2,3,4,5])
print(ar1[2])
print(ar1[-1])

3
5


In [138]:
# 2d array

ar2 = np.array([[5,4,3], [2,7,1]])
print(ar2[0,2])
print(ar2[-1,-1])

3
1


In [147]:
# 3d array

ar3 = np.array([[[1,2],[6,7]]])
print(ar3.ndim)
print(ar3[0,1,0])
print(ar3[0,0,1])

3
6
2


# Slicing

In [160]:
# 1d array

a1 = np.array([1,2,3,4,5,6,7,8,9])
print(a1[2:5:1])
print(a1[2:8:2])
print(a1[2:5])
print(a1[4:])
print(a1[:5])
print(a1[::-1])

[3 4 5]
[3 5 7]
[3 4 5]
[5 6 7 8 9]
[1 2 3 4 5]
[9 8 7 6 5 4 3 2 1]


In [165]:
# 2d array

a2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a2[0,1:])
print(a2[3,1:2])
print(a2[0:2,1:3])
print(a2[-1,0:2])
print(a2[1::2,0::2])

[2 3 4]
[14]
[[2 3]
 [6 7]]
[13 14]
[[ 5  7]
 [13 15]]


# Iteration

In [166]:
import numpy as np

In [169]:
# 1d array

ar = np.array([1,2,3,4,5,6,7,8,9])
print(ar)
print()
for i in ar:
    print(i)

[1 2 3 4 5 6 7 8 9]

1
2
3
4
5
6
7
8
9


In [174]:
# 2d array

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print()

for i in arr:
    print(i)

print()

for i in arr:
    for j in i:
        print(j)

[[1 2 3]
 [4 5 6]]

[1 2 3]
[4 5 6]

1
2
3
4
5
6


In [178]:
# 3d arrays

arrr = np.array([[[1,2,3,4,5]]])

print(arrr)
print()

for i in arrr:
    print(i)

print()

for i in arrr:
    for j in i:
        print(j)

print()

for i in arrr:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4 5]]]

[[1 2 3 4 5]]

[1 2 3 4 5]

1
2
3
4
5


In [181]:
# nditer function

arrr = np.array([[[23,54,21,324,3,4]]])

print(arrr)
print()

for i in np.nditer(arrr):
    print(i)

[[[ 23  54  21 324   3   4]]]

23
54
21
324
3
4


In [184]:
arrr = np.array([[[23,54,21,324,3,4]]])

print(arrr)
print()

for pos, i in np.ndenumerate(arrr):
    print(i, pos)

[[[ 23  54  21 324   3   4]]]

23 (0, 0, 0)
54 (0, 0, 1)
21 (0, 0, 2)
324 (0, 0, 3)
3 (0, 0, 4)
4 (0, 0, 5)


# Copy and View

In [185]:
import numpy as np

In [186]:
ar = np.array([1,2,3,4,5])
print(ar)

[1 2 3 4 5]


In [189]:
cop = ar.copy()
print(cop)

[1 2 3 4 5]


In [190]:
vw = ar.view()
print(vw)

[1 2 3 4 5]


# Join

In [1]:
import numpy as np

In [6]:
# 1d arrays

ar1 = np.array([1,2,3,4])
ar2 = np.array([6,5,4,3])

nar = np.concatenate([ar1,ar2])
print(nar)

[1 2 3 4 6 5 4 3]


In [11]:
# 2d arrays
# axis = 1 (merge the rows together in a single row)
# axis = 0 (merge the rows together)

ar2d = np.array([[1,2,3,4],[3,2,4,1]])
ar2d2 = np.array([[2,2,2,2],[4,5,3,6]])
print(ar2d)
print()
print(ar2d2)
print()

nar2 = np.concatenate([ar2d,ar2d2], axis = 1)
print(nar2)
print()
nar2 = np.concatenate([ar2d,ar2d2], axis = 0)
print(nar2)

[[1 2 3 4]
 [3 2 4 1]]

[[2 2 2 2]
 [4 5 3 6]]

[[1 2 3 4 2 2 2 2]
 [3 2 4 1 4 5 3 6]]

[[1 2 3 4]
 [3 2 4 1]
 [2 2 2 2]
 [4 5 3 6]]


In [22]:
# vstack - column merge (axis = 0)
# dstack - height merge
# hstack - rows merge (axis = 1)

ar2d = np.array([1,2,3,4])
ar2d2 = np.array([2,2,2,2])

nar = np.hstack([ar2d,ar2d2]) # rows
print(nar)

nar = np.vstack([ar2d,ar2d2]) # columns
print(nar)

nar = np.dstack([ar2d,ar2d2]) # height
print(nar)

[1 2 3 4 2 2 2 2]
[[1 2 3 4]
 [2 2 2 2]]
[[[1 2]
  [2 2]
  [3 2]
  [4 2]]]


# Split

In [23]:
import numpy as np

In [24]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [41]:
ar = np.array_split(arr,7)
print(ar)
print(ar[1])
print(type(ar))

[array([1]), array([2]), array([3]), array([4]), array([5]), array([], dtype=int32), array([], dtype=int32)]
[2]
<class 'list'>


In [44]:
ar1 = np.array([[1,2],[3,4],[5,6]])
nar = np.array_split(ar1,3)
print(nar)
narr = np.array_split(ar1, 2, axis = 1)
print(narr)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


# Search

In [45]:
import numpy as np

In [51]:
var = np.array([1,2,3,2,4,7,3,1])
ind = np.where(var%2 == 0)
print(ind)
print(ind[0])

(array([1, 3, 4], dtype=int64),)
[1 3 4]


# Search Sorted

In [52]:
import numpy as np

In [56]:
sar = np.array([1,2,3,4,5,6,7,8])
vind = np.searchsorted(sar, 6)
print(vind)

5


In [57]:
sar = np.array([1,2,3,4,5,6,7,8])
vind = np.searchsorted(sar, 6, side="right")
print(vind)

6


In [59]:
sar = np.array([1,2,3,4,5,6,7,8])
vind = np.searchsorted(sar, [2,6,1])
print(vind)

[1 5 0]


# Sort

In [60]:
import numpy as np

In [61]:
vr = np.array([2,4,1,6,8,1,6])
nar = np.sort(vr)
print(nar)

[1 1 2 4 6 6 8]


In [62]:
vr = np.array(["t","a","n","a","y"])
nar = np.sort(vr)
print(nar)

['a' 'a' 'n' 't' 'y']


In [63]:
vr = np.array([[2,4,1,3],[5,6,1,3]])
nar = np.sort(vr)
print(nar)

[[1 2 3 4]
 [1 3 5 6]]


# Filter

In [64]:
import numpy as np

In [68]:
vr = np.array([2,4,1])
f = [True, False, True]
nar = vr[f]
print(nar)

[2 1]


In [69]:
vr = np.array([2,4,1])
f = [True, False, True]
nar = vr[[True, False, True]]
print(nar)

[2 1]


# Shuffle

In [70]:
import numpy as np

arr = np.array([1,2,3,4,5])

np.random.shuffle(arr)

print(arr)

# Unique

In [76]:
import numpy as np

In [77]:
arr = np.array([1,1,2,4,11,1,3,1])

nar = np.unique(arr)
print(nar)

[ 1  2  3  4 11]


In [80]:
arr = np.array([1,1,2,4,11,1,3,1])

nar = np.unique(arr, return_index = True, return_counts = True)
print(nar)

(array([ 1,  2,  3,  4, 11]), array([0, 2, 6, 3, 4], dtype=int64), array([4, 1, 1, 1, 1], dtype=int64))


# Resize

In [81]:
import numpy as np

In [84]:
arr = np.array([1,1,2,4,11,1,3,1])

nar = np.resize(arr,(4,3))
print(nar)

[[ 1  1  2]
 [ 4 11  1]
 [ 3  1  1]
 [ 1  2  4]]


# Flatten

In [85]:
import numpy as np

In [90]:
arr = np.array([[1,2,3,4],[5,4,23,4]])
print(arr)
print(arr.flatten())
print(arr.flatten(order = "F"))
print(arr.flatten(order = "C"))

[[ 1  2  3  4]
 [ 5  4 23  4]]
[ 1  2  3  4  5  4 23  4]
[ 1  5  2  4  3 23  4  4]
[ 1  2  3  4  5  4 23  4]


# Ravel

In [92]:
print(arr.ravel(order = "F"))

[ 1  5  2  4  3 23  4  4]


# Insert

In [93]:
import numpy as np

In [94]:
arr = np.array([1,1,2,4,11,1,3,1])
print(arr)

[ 1  1  2  4 11  1  3  1]


In [99]:
nar = np.insert(arr,[2,5,1],[1,6,3])
print(nar)

[ 1  3  1  1  2  4 11  6  1  3  1]


In [107]:
# 2d arrays
# axis = 0 (new rom added)
# axis = 1 (new column added)

var = np.array([[1,2,3],[4,5,3]])

nvar = np.insert(var, 2, [45,55,31], axis = 0)
print(nvar)

nvar = np.insert(var, 2, 6, axis = 1)
print(nvar)

[[ 1  2  3]
 [ 4  5  3]
 [45 55 31]]
[[1 2 6 3]
 [4 5 6 3]]


# Delete

In [108]:
import numpy as np

In [111]:
arr = np.array([1,1,2,4,11,1,3,1])

nar = np.delete(arr, 3)
print(ar)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([], dtype=int32), array([], dtype=int32)]


# Matrix in numpy

In [112]:
import numpy as np

In [123]:
arr = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.matrix([[2,3,2],[4,3,1],[8,3,1]])
print(arr)
print()
print(np.multiply(arr,arr2))
print()
print(arr.dot(arr2)) # matrix multiplication)
print()
print(type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 2  6  6]
 [16 15  6]
 [56 24  9]]

[[ 34  18   7]
 [ 76  45  19]
 [118  72  31]]

<class 'numpy.matrix'>


In [126]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[2,3,2],[4,3,1],[8,3,1]])
print(arr)
print()
print(np.multiply(arr,arr2))
print()
print(arr.dot(arr2)) # matrix multiplication)
print(type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 2  6  6]
 [16 15  6]
 [56 24  9]]

[[ 34  18   7]
 [ 76  45  19]
 [118  72  31]]
<class 'numpy.ndarray'>
