## Numpy Practice Day 1

In [2]:
import numpy as np

In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(type(arr))
print(np.ndim(arr))
print(arr[0:2, 1:3])
print(arr.dtype)

[[b'1' b'2' b'3' b'4' b'5']
 [b'6' b'7' b'8' b'9' b'10']]
<class 'numpy.ndarray'>
2
[[b'2' b'3']
 [b'7' b'8']]
|S2


In [25]:
a = np.array([1, 2, 3, 4, 5])

x = a.copy()
y = a.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [36]:
xx = np.array([1,2,3,4,5,6,7,8], ndmin=5)
print(xx.shape)
newxx = xx.reshape(2,2,-1)
print(newxx)

arrr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arrr.reshape(-1)

print(newarr)

(1, 1, 1, 1, 8)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6]


## Questions

1. Create a NumPy array containing the numbers 1 to 5.
2. Create a 2D NumPy array with shape (3, 3) filled with zeros.
3. Access the element at index 2 in a NumPy array.
4. Slice the first three elements from a NumPy array.
5. Create a NumPy array with data type 'float64'.
6. Create a view of a NumPy array and modify its elements. Check if the original array is also modified.
7. Check the shape of a NumPy array.
8. Reshape a 1D NumPy array into a 2D array with shape (2, 3).
9. Iterate over elements of a NumPy array using a loop.
10. Concatenate two NumPy arrays vertically.
11. Split a NumPy array into three equal parts.
12. Search for the index of a specific element in a NumPy array.
13. Sort a NumPy array in ascending order.
14. Filter elements greater than 5 from a NumPy array.
15. Create a NumPy array containing only even numbers from 1 to 10.
16. Create a 2D NumPy array filled with random integers between 0 and 10.
17. Find the maximum element in a NumPy array.
18. Find the mean of a NumPy array.
19. Calculate the sum of all elements in a NumPy array.
20. Check if any element in a NumPy array is zero.
21. Convert a Python list to a NumPy array.
22. Extract all odd numbers from a NumPy array.
23. Remove duplicate elements from a NumPy array.
24. Compute the dot product of two NumPy arrays.
25. Transpose a 2D NumPy array.
26. Add a constant value to each element of a NumPy array.
27. Find the unique elements in a NumPy array.
28. Create a 3x3 identity matrix using NumPy.
29. Replace all negative elements in a NumPy array with zero.
30. Check if two NumPy arrays are equal.
