## Numpy Practice

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
x = [1,2,3,4,5]
y = np.array(x)

In [5]:
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
ar2 = np.array([[1,2,3,4], [5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [10]:
ar3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [13]:
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [14]:
import numpy as np

In [18]:
ar_zero = np.zeros(4)
ar_2z = np.zeros((3,4))
print(ar_zero)
print()
print(ar_2z)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
ar_one = np.ones(5)
ar_2one = np.ones((4,2))
print(ar_one)
print()
print(ar_2one)

[1. 1. 1. 1. 1.]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
ar_em = np.empty(5)
print(ar_em)

[1. 1. 1. 1. 1.]


In [25]:
ar_rng = np.arange(5)
print(ar_rng)

[0 1 2 3 4]


In [30]:
ar_dia = np.eye(4,4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
ar_lin = np.linspace(0,10, num = 5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]
