## Numpy Practice

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
x = [1,2,3,4,5]
y = np.array(x)

In [5]:
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
ar2 = np.array([[1,2,3,4], [5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [10]:
ar3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [13]:
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Special numpy arrays

In [14]:
import numpy as np

In [18]:
ar_zero = np.zeros(4)
ar_2z = np.zeros((3,4))
print(ar_zero)
print()
print(ar_2z)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
ar_one = np.ones(5)
ar_2one = np.ones((4,2))
print(ar_one)
print()
print(ar_2one)

[1. 1. 1. 1. 1.]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
ar_em = np.empty(5)
print(ar_em)

[1. 1. 1. 1. 1.]


In [25]:
ar_rng = np.arange(5)
print(ar_rng)

[0 1 2 3 4]


In [30]:
ar_dia = np.eye(4,4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
ar_lin = np.linspace(0,20, num = 5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# Random functions

In [34]:
import numpy as np

In [35]:
var = np.random.rand(4)
print(var)

[0.99177407 0.25416304 0.72603762 0.19877428]


In [36]:
var1 = np.random.rand(2,5)
print(var1)

[[0.58764975 0.75670403 0.96925159 0.1805577  0.94636683]
 [0.87335347 0.92395493 0.61747188 0.90401706 0.14741869]]


In [37]:
varn = np.random.randn(5)
print(varn)

[ 1.09368511  0.22966137  0.02615756 -2.14902563  0.74878239]


In [38]:
varnd = np.random.randn(3,4)
print(varnd)

[[ 1.25417603 -1.16851994  0.62973363 -0.54062229]
 [ 0.35662221  0.24974486 -0.21078632 -0.03483389]
 [ 0.23108073  1.8352828  -0.43000531 -0.61370377]]


In [39]:
varf = np.random.ranf(4)
print(varf)

[0.35652869 0.97374752 0.70756212 0.04898589]


In [45]:
varr = np.random.randint(5, 20, 5)
print(varr)

[17 10  9 19 10]


# Data Types

In [46]:
import numpy as np

In [50]:
var = np.array([1,"2",3,4,5])
print("Data type: ", var.dtype)

Data type:  <U11


In [58]:
arrd = np.array([1,2,3,4], dtype = "f")
print(arrd.dtype)

float32


In [59]:
varty = arrd.astype(int)
print(arrd)
print(varty)

[1. 2. 3. 4.]
[1 2 3 4]


# Shaping and Reshaping of numpy arrays

In [60]:
import numpy as np

In [63]:
vars = np.array([[1,2,3],[4,5,6]])
print(vars)
print()
print(vars.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [67]:
varmul = np.array([1,2,3], ndmin = 7)
print(varmul)
print()
print(varmul.shape)

[[[[[[[1 2 3]]]]]]]

(1, 1, 1, 1, 1, 1, 3)


In [71]:
varres = np.array([1,2,3,4,5,6])
x = varres.reshape(3,2)
print(x.ndim)
print(x.shape)
print(x)

2
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [81]:
varry = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(varry)
print(varry.ndim)
print(varry.shape)
print()
vres = varry.reshape(2,3,2)
print(vres)
print(vres.ndim)
print(vres.shape)
print()
v1 = vres.reshape(-1)
print(v1)
print(v1.ndim)
print(v1.shape)
print()

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)

